

services:
    rabbitmq:
      image: rabbitmq:management
      container_name: RabbitMQ
      hostname: RabbitMQ
      environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: admin
      restart: always
      ports:
      - "5672:5672"
      - "15672:15672"
      volumes:
      - db-data:/var/lib/rabbitmq
      - logs:/var/log/rabbitmq
      - metrics:/var/lib/rabbitmq/metrics
      networks:
      - backend
    backend:
      build: .
      ports:
      - "3000:3000"
      container_name: backend
      networks: 
      - backend
      depends_on:
      - rabbitmq
      restart: always
    postgresql:
      image: postgres:latest
      container_name: postgresql
      hostname: postgresql
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: database
      restart: always
      ports:
      - "5432:5432"
      volumes:
      - logs:/var/lib/postgresql/logs
      - data:/var/lib/postgresql/data
      - metrics:/var/lib/postgresql/metrics
      networks:
      - backend
    consumer:
      networks:
      - backend
      depends_on:
      - rabbitmq
      - postgresql
      build: 
        context: .
        dockerfile: Dockerfile.consumer
      restart: always

volumes:
  db-data: 
  logs: 
  metrics: 
  data:

networks:
  backend: 
    driver: bridge
